spring:
  application:
    name: observation_project

  datasource:
    url: jdbc:h2:mem:observationdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
    show-sql: true

  h2:
    console:
      enabled: true